apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  SPRING_PROFILES_ACTIVE: kube
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_URL: jdbc:postgresql://192.168.1.19:5432/fraud
  SPRING_DATASOURCE_PASSWORD: sasa
  